[language_server.clangd]
filetypes = ["c", "cpp"]
root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
command = "clangd"

[language_server.haskell-language-server]
filetypes = ["haskell"]
root_globs = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language_server.clojure-lsp]
filetypes = ["clojure"]
root_globs = ["shadow-cljs.edn", "deps.edn", "project.clj", ".git", ".hg"]
command = "clojure-lsp"
settings_section = "_"
[language_server.clojure-lsp.settings._]

[language_server.rust-analyzer]
filetypes = ["rust"]
root_globs = ["Cargo.toml"]
command = "sh"
args = ["-c", """
        if path=$(rustup which rust-analyzer 2>/dev/null); then
            "$path"
        else
            RA_LOG=rust_analyzer=info rust-analyzer | tee /tmp/ra.log
        fi
    """]
settings_section = "rust-analyzer"
[language_server.rust-analyzer.settings.rust-analyzer]
hoverActions.enable = false
hover.linksInHover = true
cargo.loadOutDirsFromCheck = true
procMacro.enable = true

[language_server.pylsp]
filetypes = ["python"]
root_globs = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"
offset_encoding = "utf-8"
settings_section = "_"
[language_server.pylsp.settings._]
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.mccabe.enabled = false
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.flake8.enabled = true
pylsp.configurationSources = ["flake8"]

[language_server.typescript-language-server]
filetypes = ["typescript", "javascript"]
root_globs = ["package.json", "tsconfig.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language_server.nimlangserver]
filetypes = ["nim"]
root_globs = ["*.nimble", ".git", ".hg"]
command = "nimlangserver"

[language_server.zls]
filetypes = ["zig"]
root_globs = ["build.zig"]
command = "zls"

[language_server.nil]
filetypes = ["nix"]
root_globs = ["flake.nix", "shell.nix", ".git", ".hg"]
command = "nil"
